name: MarketPlace
version: 1.21.4
main: com.example.trial.MarketPlace
api-version: 1.21
commands:
  sell:
    description: List the item in your hand for sale.
    usage: /sell <price>
  marketplace:
    description: View the marketplace.
    usage: /marketplace
  blackmarket:
    description: Refresh and view the black market.
    usage: /blackmarket
  transactions:
    description: View your transaction history.
    usage: /transactions
depend: [Vault]
